- principal: emegirdigital@outlook.com
  privileges:
    - USE CATALOG
    - CREATE SCHEMA
    - SELECT

- principal: arn:aws:iam::123456789012:user/lakehouse-sp-ml
  privileges:
    - SELECT

- principal: arn:aws:iam::123456789012:user/lakehouse-sp-ingest
  privileges:
    - CREATE TABLE
    - SELECT
