- principal: emegirdigital@outlook.com
  catalog_privileges:
    - USE CATALOG
    - CREATE SCHEMA
  schema_privileges:
    - SELECT

- principal: arn:aws:iam::123456789012:user/lakehouse-sp-ml
  schema_privileges:
    - SELECT
