catalogs:
  - name: lakehouse_catalog
    comment: "Lakehouse accelerator catalog"

schemas:
  - name: bronze
    catalog: dev_catalog

  - name: silver
    catalog: dev_catalog

  - name: gold
    catalog: dev_catalog
