catalogs:
  - name: lakehouse_catalog
    comment: "Lakehouse accelerator catalog for schema organization"

schemas:
  - name: bronze
    catalog: lakehouse_catalog

  - name: silver
    catalog: lakehouse_catalog

  - name: gold
    catalog: lakehouse_catalog