catalogs:
  - name: ${var.uc_catalog}
    comment: "Lakehouse accelerator catalog"

schemas:
  - name: bronze
    catalog: ${var.uc_catalog}
  - name: silver
    catalog: ${var.uc_catalog}
  - name: gold
    catalog: ${var.uc_catalog}

grants:
  - principal: ${var.sp_id}
    privileges: ["USE CATALOG", "CREATE SCHEMA", "CREATE TABLE", "SELECT"]
