[project]
name = "lakehouse_accelerator"
version = "0.1.0"
description = "Lakehouse accelerator for Unity Catalog bootstrap"
dependencies = [
    "databricks-sdk>=0.15.0",
    "pyyaml"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
