name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Install Python dependencies
        run: |
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Install Databricks CLI (binary release)
        shell: bash
        run: |
          set -e
          VERSION="0.274.0"
          FILE="databricks_cli_${VERSION}_linux_amd64"
          curl -fsSL -O "https://github.com/databricks/cli/releases/download/v${VERSION}/${FILE}.zip"
          unzip -q "${FILE}.zip" -d $RUNNER_TEMP/.bin
          chmod +x "$RUNNER_TEMP/.bin/databricks"
          echo "$RUNNER_TEMP/.bin" >> $GITHUB_PATH

      - name: Install uv (Python package manager)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Confirm Databricks environment variables
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Databricks host: $DATABRICKS_HOST"
          echo "Databricks token is set: ${#DATABRICKS_TOKEN} characters"

      - name: Validate Databricks bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          cd lakehouse_accelerator
          databricks bundle validate --target dev

      - name: Deploy Databricks bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle deploy --target dev

      - name: Run Databricks bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          cd lakehouse_accelerator
          databricks bundle run --target dev
