name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Install dependencies
        run: |
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Install Databricks CLI
        run: |
          . .venv/bin/activate
          pip install databricks-cli

      - name: Configure Databricks CLI (non-interactive)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          . .venv/bin/activate
          mkdir -p ~/.databricks
          echo "[default]" > ~/.databricks/config
          echo "host = $DATABRICKS_HOST" >> ~/.databricks/config
          echo "token = $DATABRICKS_TOKEN" >> ~/.databricks/config
  
      - name: Validate Databricks bundle
        run: |
          . .venv/bin/activate
          databricks bundle validate --target dev
